In [5]:
import spacy
nlp = spacy.load('en_core_web_sm')
tokens = nlp(u'He has obstructed the Administration of Justice, by refusing his Assent to Laws for establishing Judiciary powers.')

In [6]:
tokens.vector

array([-0.11425088, -0.10413295, -0.24282165,  0.21275578,  0.00749772,
       -0.02474931,  0.45621705, -0.41841638,  0.05420694,  0.09403116,
       -0.05572187, -0.07268924, -0.3064064 , -0.06167271,  0.15748703,
       -0.03253493, -0.24706845,  0.30903396,  0.36214343, -0.29595858,
       -0.15359084,  0.09930561,  0.02290563, -0.10290851,  0.39759627,
       -0.17267746,  0.34479076,  0.03763293,  0.06557416,  0.3229541 ,
       -0.12550916,  0.20096959,  0.14495867,  0.0422615 , -0.45419282,
       -0.12093291,  0.07911193,  0.27623066,  0.15021968, -0.01095563,
        0.21005386, -0.06624435, -0.28096497,  0.11158957,  0.32392016,
        0.25774154,  0.23901977, -0.05218179,  0.4642578 , -0.21502116,
       -0.22616386,  0.07133435, -0.22549665, -0.4578599 , -0.5553237 ,
       -0.35779652, -0.16841893, -0.08252573,  0.15830301, -0.15943006,
        0.00965384, -0.14887105,  0.2076914 ,  0.04962179,  0.10589492,
        0.21845989,  0.4222003 , -0.18592219, -0.2214833 ,  0.29546687,
       -0.13696365, -0.27461073,  0.09691102, -0.01818589,  0.01447877,
       -0.3725112 , -0.37594888, -0.10864514, -0.15284   , -0.14816107,
        0.06240889,  0.20072842, -0.20421705, -0.22200012,  0.31241646,
        0.16559924,  0.20358077,  0.16712153, -0.29777363,  0.37727925,
       -0.34937406,  0.19103992,  0.35851976, -0.04019548, -0.12355476,
       -0.02069735], dtype=float32)

In [7]:
for token1 in tokens:
  for token2 in tokens:
    print(token1.text,token2.text,token1.similarity(token2))

He He 1.0
He has -0.0627966970205307
He obstructed -0.019354887306690216
He the -0.0015055901603773236
He Administration 0.07920248806476593
He of 0.06500546634197235
He Justice 0.03519656881690025
He , -0.16933298110961914
He by -0.10326580703258514
He refusing -0.1166396364569664
He his 0.0701289176940918
He Assent 0.11195669323205948
He to 0.011840078048408031
He Laws -0.019595548510551453
He for -0.11343364417552948
He establishing -0.12273681163787842
He Judiciary 0.01754218153655529
He powers 0.03082350082695484
He . 0.062240079045295715
has He -0.0627966970205307
has has 1.0
has obstructed 0.009802959859371185
has the -0.004056387580931187
has Administration -0.27465566992759705
has of 0.0175989530980587
has Justice -0.11038980633020401
has , 0.1423492282629013
has by -0.035858187824487686
has refusing 0.08782444149255753
has his -0.012009238824248314
has Assent -0.28304317593574524
has to 0.05812615901231766
has Laws -0.11555874347686768
has for -0.036121219396591187
has establishing -0.035542454570531845
has Judiciary -0.07873377203941345
has powers 0.1526309996843338
has . -0.09198963642120361
obstructed He -0.019354887306690216
obstructed has 0.009802959859371185
obstructed obstructed 1.0
obstructed the -0.04094827175140381
obstructed Administration 0.15539610385894775
obstructed of 0.017506523057818413
obstructed Justice 0.05745293200016022
obstructed , -0.08600136637687683
obstructed by 0.08427584171295166
obstructed refusing 0.22837986052036285
obstructed his -0.08032127469778061
obstructed Assent 0.1677071750164032
obstructed to 0.12682762742042542
obstructed Laws 0.021703431382775307
obstructed for -0.040256064385175705
obstructed establishing 0.25952988862991333
obstructed Judiciary -0.0863846018910408
obstructed powers -0.0520632266998291
obstructed . -0.06122647598385811
the He -0.0015055901603773236
the has -0.004056387580931187
the obstructed -0.04094827175140381
the the 1.0
the Administration 0.004089050460606813
the of 0.06914468854665756
the Justice 0.018153535202145576
the , -0.0490020252764225
the by -0.13078586757183075
the refusing -0.07762499153614044
the his 0.45893123745918274
the Assent -0.03179140016436577
the to -0.035745829343795776
the Laws 0.05897378921508789
the for -0.09844594448804855
the establishing 0.06620695441961288
the Judiciary 0.22787219285964966
the powers -0.06940145045518875
the . -0.13027465343475342
Administration He 0.07920248806476593
Administration has -0.27465566992759705
Administration obstructed 0.15539610385894775
Administration the 0.004089050460606813
Administration Administration 1.0
Administration of 0.0720435082912445
Administration Justice 0.5683599710464478
Administration , -0.1639430969953537
Administration by -0.03347976505756378
Administration refusing 0.021487031131982803
Administration his -0.051887109875679016
Administration Assent 0.6786361932754517
Administration to 0.09837575256824493
Administration Laws 0.46121662855148315
Administration for 0.06626641750335693
Administration establishing 0.059049319475889206
Administration Judiciary 0.4097144603729248
Administration powers 0.36989080905914307
Administration . -0.04870780557394028
of He 0.06500546634197235
of has 0.0175989530980587
of obstructed 0.017506523057818413
of the 0.06914468854665756
of Administration 0.0720435082912445
of of 1.0
of Justice 0.05226970091462135
of , -0.020508231595158577
of by 0.1454140841960907
of refusing -0.06251483410596848
of his -0.061869025230407715
of Assent -0.0068812589161098
of to 0.5930981636047363
of Laws -0.06824896484613419
of for 0.348935604095459
of establishing 0.036236394196748734
of Judiciary -0.17418202757835388
of powers -0.1321050524711609
of . -0.1313222348690033
Justice He 0.03519656881690025
Justice has -0.11038980633020401
Justice obstructed 0.05745293200016022
Justice the 0.018153535202145576
Justice Administration 0.5683599710464478
Justice of 0.05226970091462135
Justice Justice 1.0
Justice , 0.11621879786252975
Justice by -0.12223248183727264
Justice refusing 0.013648374937474728
Justice his 0.043595585972070694
Justice Assent 0.5354931950569153
Justice to 0.11606629937887192
Justice Laws 0.6077650785446167
Justice for -0.09655877947807312
Justice establishing 0.12529711425304413
Justice Judiciary 0.35603389143943787
Justice powers 0.48633483052253723
Justice . 0.08107177168130875
, He -0.16933298110961914
, has 0.1423492282629013
, obstructed -0.08600136637687683
, the -0.0490020252764225
, Administration -0.1639430969953537
, of -0.020508231595158577
, Justice 0.11621879786252975
, , 1.0
, by 0.02578815445303917
, refusing -0.0692383423447609
, his -0.020476246252655983
, Assent -0.062187641859054565
, to 0.03085121512413025
, Laws -0.0013535211328417063
, for 0.03443268686532974
, establishing -0.06270357966423035
, Judiciary -0.13688130676746368
, powers 0.008192997425794601
, . 0.19742290675640106
by He -0.10326580703258514
by has -0.035858187824487686
by obstructed 0.08427584171295166
by the -0.13078586757183075
by Administration -0.03347976505756378
by of 0.1454140841960907
by Justice -0.12223248183727264
by , 0.02578815445303917
by by 1.0
by refusing 0.07632245868444443
by his -0.23390313982963562
by Assent -0.1288459748029709
by to 0.37149086594581604
by Laws -0.11625974625349045
by for 0.6364860534667969
by establishing 0.048063185065984726
by Judiciary -0.03677239641547203
by powers -0.13180547952651978
by . -0.08377859741449356
refusing He -0.1166396364569664
refusing has 0.08782444149255753
refusing obstructed 0.22837986052036285
refusing the -0.07762499153614044
refusing Administration 0.021487031131982803
refusing of -0.06251483410596848
refusing Justice 0.013648374937474728
refusing , -0.0692383423447609
refusing by 0.07632245868444443
refusing refusing 1.0
refusing his 0.10422632843255997
refusing Assent 0.044070206582546234
refusing to 0.03548382595181465
refusing Laws -0.002575384918600321
refusing for 0.07256384193897247
refusing establishing 0.7976226806640625
refusing Judiciary -0.1051662489771843
refusing powers 0.09955502301454544
refusing . -0.07133384048938751
his He 0.0701289176940918
his has -0.012009238824248314
his obstructed -0.08032127469778061
his the 0.45893123745918274
his Administration -0.051887109875679016
his of -0.061869025230407715
his Justice 0.043595585972070694
his , -0.020476246252655983
his by -0.23390313982963562
his refusing 0.10422632843255997
his his 1.0
his Assent 0.024633852764964104
his to -0.027592618018388748
his Laws 0.03835239261388779
his for -0.1526133418083191
his establishing 0.13885195553302765
his Judiciary 0.07666492462158203
his powers 0.02314138226211071
his . -0.010542819276452065
Assent He 0.11195669323205948
Assent has -0.28304317593574524
Assent obstructed 0.1677071750164032
Assent the -0.03179140016436577
Assent Administration 0.6786361932754517
Assent of -0.0068812589161098
Assent Justice 0.5354931950569153
Assent , -0.062187641859054565
Assent by -0.1288459748029709
Assent refusing 0.044070206582546234
Assent his 0.024633852764964104
Assent Assent 1.0
Assent to 0.1540781557559967
Assent Laws 0.4636166989803314
Assent for -0.04299314692616463
Assent establishing 0.08366068452596664
Assent Judiciary 0.33100831508636475
Assent powers 0.452600359916687
Assent . -0.0006241434602998197
to He 0.011840078048408031
to has 0.05812615901231766
to obstructed 0.12682762742042542
to the -0.035745829343795776
to Administration 0.09837575256824493
to of 0.5930981636047363
to Justice 0.11606629937887192
to , 0.03085121512413025
to by 0.37149086594581604
to refusing 0.03548382595181465
to his -0.027592618018388748
to Assent 0.1540781557559967
to to 1.0
to Laws 0.02138262800872326
to for 0.47542670369148254
to establishing 0.12556439638137817
to Judiciary -0.07168252766132355
to powers -0.016174441203475
to . 0.0029932924080640078
Laws He -0.019595548510551453
Laws has -0.11555874347686768
Laws obstructed 0.021703431382775307
Laws the 0.05897378921508789
Laws Administration 0.46121662855148315
Laws of -0.06824896484613419
Laws Justice 0.6077650785446167
Laws , -0.0013535211328417063
Laws by -0.11625974625349045
Laws refusing -0.002575384918600321
Laws his 0.03835239261388779
Laws Assent 0.4636166989803314
Laws to 0.02138262800872326
Laws Laws 1.0
Laws for -0.04321127012372017
Laws establishing 0.02832735888659954
Laws Judiciary 0.31756702065467834
Laws powers 0.57756507396698
Laws . 0.002839137567207217
for He -0.11343364417552948
for has -0.036121219396591187
for obstructed -0.040256064385175705
for the -0.09844594448804855
for Administration 0.06626641750335693
for of 0.348935604095459
for Justice -0.09655877947807312
for , 0.03443268686532974
for by 0.6364860534667969
for refusing 0.07256384193897247
for his -0.1526133418083191
for Assent -0.04299314692616463
for to 0.47542670369148254
for Laws -0.04321127012372017
for for 1.0
for establishing 0.1183067113161087
for Judiciary -0.0014962432906031609
for powers -0.09978631883859634
for . -0.019388346001505852
establishing He -0.12273681163787842
establishing has -0.035542454570531845
establishing obstructed 0.25952988862991333
establishing the 0.06620695441961288
establishing Administration 0.059049319475889206
establishing of 0.036236394196748734
establishing Justice 0.12529711425304413
establishing , -0.06270357966423035
establishing by 0.048063185065984726
establishing refusing 0.7976226806640625
establishing his 0.13885195553302765
establishing Assent 0.08366068452596664
establishing to 0.12556439638137817
establishing Laws 0.02832735888659954
establishing for 0.1183067113161087
establishing establishing 1.0
establishing Judiciary 0.009940973483026028
establishing powers 0.04976572096347809
establishing . -0.15943609178066254
Judiciary He 0.01754218153655529
Judiciary has -0.07873377203941345
Judiciary obstructed -0.0863846018910408
Judiciary the 0.22787219285964966
Judiciary Administration 0.4097144603729248
Judiciary of -0.17418202757835388
Judiciary Justice 0.35603389143943787
Judiciary , -0.13688130676746368
Judiciary by -0.03677239641547203
Judiciary refusing -0.1051662489771843
Judiciary his 0.07666492462158203
Judiciary Assent 0.33100831508636475
Judiciary to -0.07168252766132355
Judiciary Laws 0.31756702065467834
Judiciary for -0.0014962432906031609
Judiciary establishing 0.009940973483026028
Judiciary Judiciary 1.0
Judiciary powers 0.2819235026836395
Judiciary . -0.015380841679871082
powers He 0.03082350082695484
powers has 0.1526309996843338
powers obstructed -0.0520632266998291
powers the -0.06940145045518875
powers Administration 0.36989080905914307
powers of -0.1321050524711609
powers Justice 0.48633483052253723
powers , 0.008192997425794601
powers by -0.13180547952651978
powers refusing 0.09955502301454544
powers his 0.02314138226211071
powers Assent 0.452600359916687
powers to -0.016174441203475
powers Laws 0.57756507396698
powers for -0.09978631883859634
powers establishing 0.04976572096347809
powers Judiciary 0.2819235026836395
powers powers 1.0
powers . 0.0008433759212493896
. He 0.062240079045295715
. has -0.09198963642120361
. obstructed -0.06122647598385811
. the -0.13027465343475342
. Administration -0.04870780557394028
. of -0.1313222348690033
. Justice 0.08107177168130875
. , 0.19742290675640106
. by -0.08377859741449356
. refusing -0.07133384048938751
. his -0.010542819276452065
. Assent -0.0006241434602998197
. to 0.0029932924080640078
. Laws 0.002839137567207217
. for -0.019388346001505852
. establishing -0.15943609178066254
. Judiciary -0.015380841679871082
. powers 0.0008433759212493896
. . 1.0

/tmp/ipython-input-558/914047137.py:3: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Token.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  print(token1.text,token2.text,token1.similarity(token2))

In [8]:
for token1 in tokens:
  for token2 in tokens:
    print(token1.text,token2.text,token1.similarity(token2))

He He 1.0
He has -0.0627966970205307
He obstructed -0.019354887306690216
He the -0.0015055901603773236
He Administration 0.07920248806476593
He of 0.06500546634197235
He Justice 0.03519656881690025
He , -0.16933298110961914
He by -0.10326580703258514
He refusing -0.1166396364569664
He his 0.0701289176940918
He Assent 0.11195669323205948
He to 0.011840078048408031
He Laws -0.019595548510551453
He for -0.11343364417552948
He establishing -0.12273681163787842
He Judiciary 0.01754218153655529
He powers 0.03082350082695484
He . 0.062240079045295715
has He -0.0627966970205307
has has 1.0
has obstructed 0.009802959859371185
has the -0.004056387580931187
has Administration -0.27465566992759705
has of 0.0175989530980587
has Justice -0.11038980633020401
has , 0.1423492282629013
has by -0.035858187824487686
has refusing 0.08782444149255753
has his -0.012009238824248314
has Assent -0.28304317593574524
has to 0.05812615901231766
has Laws -0.11555874347686768
has for -0.036121219396591187
has establishing -0.035542454570531845
has Judiciary -0.07873377203941345
has powers 0.1526309996843338
has . -0.09198963642120361
obstructed He -0.019354887306690216
obstructed has 0.009802959859371185
obstructed obstructed 1.0
obstructed the -0.04094827175140381
obstructed Administration 0.15539610385894775
obstructed of 0.017506523057818413
obstructed Justice 0.05745293200016022
obstructed , -0.08600136637687683
obstructed by 0.08427584171295166
obstructed refusing 0.22837986052036285
obstructed his -0.08032127469778061
obstructed Assent 0.1677071750164032
obstructed to 0.12682762742042542
obstructed Laws 0.021703431382775307
obstructed for -0.040256064385175705
obstructed establishing 0.25952988862991333
obstructed Judiciary -0.0863846018910408
obstructed powers -0.0520632266998291
obstructed . -0.06122647598385811
the He -0.0015055901603773236
the has -0.004056387580931187
the obstructed -0.04094827175140381
the the 1.0
the Administration 0.004089050460606813
the of 0.06914468854665756
the Justice 0.018153535202145576
the , -0.0490020252764225
the by -0.13078586757183075
the refusing -0.07762499153614044
the his 0.45893123745918274
the Assent -0.03179140016436577
the to -0.035745829343795776
the Laws 0.05897378921508789
the for -0.09844594448804855
the establishing 0.06620695441961288
the Judiciary 0.22787219285964966
the powers -0.06940145045518875
the . -0.13027465343475342
Administration He 0.07920248806476593
Administration has -0.27465566992759705
Administration obstructed 0.15539610385894775
Administration the 0.004089050460606813
Administration Administration 1.0
Administration of 0.0720435082912445
Administration Justice 0.5683599710464478
Administration , -0.1639430969953537
Administration by -0.03347976505756378
Administration refusing 0.021487031131982803
Administration his -0.051887109875679016
Administration Assent 0.6786361932754517
Administration to 0.09837575256824493
Administration Laws 0.46121662855148315
Administration for 0.06626641750335693
Administration establishing 0.059049319475889206
Administration Judiciary 0.4097144603729248
Administration powers 0.36989080905914307
Administration . -0.04870780557394028
of He 0.06500546634197235
of has 0.0175989530980587
of obstructed 0.017506523057818413
of the 0.06914468854665756
of Administration 0.0720435082912445
of of 1.0
of Justice 0.05226970091462135
of , -0.020508231595158577
of by 0.1454140841960907
of refusing -0.06251483410596848
of his -0.061869025230407715
of Assent -0.0068812589161098
of to 0.5930981636047363
of Laws -0.06824896484613419
of for 0.348935604095459
of establishing 0.036236394196748734
of Judiciary -0.17418202757835388
of powers -0.1321050524711609
of . -0.1313222348690033
Justice He 0.03519656881690025
Justice has -0.11038980633020401
Justice obstructed 0.05745293200016022
Justice the 0.018153535202145576
Justice Administration 0.5683599710464478
Justice of 0.05226970091462135
Justice Justice 1.0
Justice , 0.11621879786252975
Justice by -0.12223248183727264
Justice refusing 0.013648374937474728
Justice his 0.043595585972070694
Justice Assent 0.5354931950569153
Justice to 0.11606629937887192
Justice Laws 0.6077650785446167
Justice for -0.09655877947807312
Justice establishing 0.12529711425304413
Justice Judiciary 0.35603389143943787
Justice powers 0.48633483052253723
Justice . 0.08107177168130875
, He -0.16933298110961914
, has 0.1423492282629013
, obstructed -0.08600136637687683
, the -0.0490020252764225
, Administration -0.1639430969953537
, of -0.020508231595158577
, Justice 0.11621879786252975
, , 1.0
, by 0.02578815445303917
, refusing -0.0692383423447609
, his -0.020476246252655983
, Assent -0.062187641859054565
, to 0.03085121512413025
, Laws -0.0013535211328417063
, for 0.03443268686532974
, establishing -0.06270357966423035
, Judiciary -0.13688130676746368
, powers 0.008192997425794601
, . 0.19742290675640106
by He -0.10326580703258514
by has -0.035858187824487686
by obstructed 0.08427584171295166
by the -0.13078586757183075
by Administration -0.03347976505756378
by of 0.1454140841960907
by Justice -0.12223248183727264
by , 0.02578815445303917
by by 1.0
by refusing 0.07632245868444443
by his -0.23390313982963562
by Assent -0.1288459748029709
by to 0.37149086594581604
by Laws -0.11625974625349045
by for 0.6364860534667969
by establishing 0.048063185065984726
by Judiciary -0.03677239641547203
by powers -0.13180547952651978
by . -0.08377859741449356
refusing He -0.1166396364569664
refusing has 0.08782444149255753
refusing obstructed 0.22837986052036285
refusing the -0.07762499153614044
refusing Administration 0.021487031131982803
refusing of -0.06251483410596848
refusing Justice 0.013648374937474728
refusing , -0.0692383423447609
refusing by 0.07632245868444443
refusing refusing 1.0
refusing his 0.10422632843255997
refusing Assent 0.044070206582546234
refusing to 0.03548382595181465
refusing Laws -0.002575384918600321
refusing for 0.07256384193897247
refusing establishing 0.7976226806640625
refusing Judiciary -0.1051662489771843
refusing powers 0.09955502301454544
refusing . -0.07133384048938751
his He 0.0701289176940918
his has -0.012009238824248314
his obstructed -0.08032127469778061
his the 0.45893123745918274
his Administration -0.051887109875679016
his of -0.061869025230407715
his Justice 0.043595585972070694
his , -0.020476246252655983
his by -0.23390313982963562
his refusing 0.10422632843255997
his his 1.0
his Assent 0.024633852764964104
his to -0.027592618018388748
his Laws 0.03835239261388779
his for -0.1526133418083191
his establishing 0.13885195553302765
his Judiciary 0.07666492462158203
his powers 0.02314138226211071
his . -0.010542819276452065
Assent He 0.11195669323205948
Assent has -0.28304317593574524
Assent obstructed 0.1677071750164032
Assent the -0.03179140016436577
Assent Administration 0.6786361932754517
Assent of -0.0068812589161098
Assent Justice 0.5354931950569153
Assent , -0.062187641859054565
Assent by -0.1288459748029709
Assent refusing 0.044070206582546234
Assent his 0.024633852764964104
Assent Assent 1.0
Assent to 0.1540781557559967
Assent Laws 0.4636166989803314
Assent for -0.04299314692616463
Assent establishing 0.08366068452596664
Assent Judiciary 0.33100831508636475
Assent powers 0.452600359916687
Assent . -0.0006241434602998197
to He 0.011840078048408031
to has 0.05812615901231766
to obstructed 0.12682762742042542
to the -0.035745829343795776
to Administration 0.09837575256824493
to of 0.5930981636047363
to Justice 0.11606629937887192
to , 0.03085121512413025
to by 0.37149086594581604
to refusing 0.03548382595181465
to his -0.027592618018388748
to Assent 0.1540781557559967
to to 1.0
to Laws 0.02138262800872326
to for 0.47542670369148254
to establishing 0.12556439638137817
to Judiciary -0.07168252766132355
to powers -0.016174441203475
to . 0.0029932924080640078
Laws He -0.019595548510551453
Laws has -0.11555874347686768
Laws obstructed 0.021703431382775307
Laws the 0.05897378921508789
Laws Administration 0.46121662855148315
Laws of -0.06824896484613419
Laws Justice 0.6077650785446167
Laws , -0.0013535211328417063
Laws by -0.11625974625349045
Laws refusing -0.002575384918600321
Laws his 0.03835239261388779
Laws Assent 0.4636166989803314
Laws to 0.02138262800872326
Laws Laws 1.0
Laws for -0.04321127012372017
Laws establishing 0.02832735888659954
Laws Judiciary 0.31756702065467834
Laws powers 0.57756507396698
Laws . 0.002839137567207217
for He -0.11343364417552948
for has -0.036121219396591187
for obstructed -0.040256064385175705
for the -0.09844594448804855
for Administration 0.06626641750335693
for of 0.348935604095459
for Justice -0.09655877947807312
for , 0.03443268686532974
for by 0.6364860534667969
for refusing 0.07256384193897247
for his -0.1526133418083191
for Assent -0.04299314692616463
for to 0.47542670369148254
for Laws -0.04321127012372017
for for 1.0
for establishing 0.1183067113161087
for Judiciary -0.0014962432906031609
for powers -0.09978631883859634
for . -0.019388346001505852
establishing He -0.12273681163787842
establishing has -0.035542454570531845
establishing obstructed 0.25952988862991333
establishing the 0.06620695441961288
establishing Administration 0.059049319475889206
establishing of 0.036236394196748734
establishing Justice 0.12529711425304413
establishing , -0.06270357966423035
establishing by 0.048063185065984726
establishing refusing 0.7976226806640625
establishing his 0.13885195553302765
establishing Assent 0.08366068452596664
establishing to 0.12556439638137817
establishing Laws 0.02832735888659954
establishing for 0.1183067113161087
establishing establishing 1.0
establishing Judiciary 0.009940973483026028
establishing powers 0.04976572096347809
establishing . -0.15943609178066254
Judiciary He 0.01754218153655529
Judiciary has -0.07873377203941345
Judiciary obstructed -0.0863846018910408
Judiciary the 0.22787219285964966
Judiciary Administration 0.4097144603729248
Judiciary of -0.17418202757835388
Judiciary Justice 0.35603389143943787
Judiciary , -0.13688130676746368
Judiciary by -0.03677239641547203
Judiciary refusing -0.1051662489771843
Judiciary his 0.07666492462158203
Judiciary Assent 0.33100831508636475
Judiciary to -0.07168252766132355
Judiciary Laws 0.31756702065467834
Judiciary for -0.0014962432906031609
Judiciary establishing 0.009940973483026028
Judiciary Judiciary 1.0
Judiciary powers 0.2819235026836395
Judiciary . -0.015380841679871082
powers He 0.03082350082695484
powers has 0.1526309996843338
powers obstructed -0.0520632266998291
powers the -0.06940145045518875
powers Administration 0.36989080905914307
powers of -0.1321050524711609
powers Justice 0.48633483052253723
powers , 0.008192997425794601
powers by -0.13180547952651978
powers refusing 0.09955502301454544
powers his 0.02314138226211071
powers Assent 0.452600359916687
powers to -0.016174441203475
powers Laws 0.57756507396698
powers for -0.09978631883859634
powers establishing 0.04976572096347809
powers Judiciary 0.2819235026836395
powers powers 1.0
powers . 0.0008433759212493896
. He 0.062240079045295715
. has -0.09198963642120361
. obstructed -0.06122647598385811
. the -0.13027465343475342
. Administration -0.04870780557394028
. of -0.1313222348690033
. Justice 0.08107177168130875
. , 0.19742290675640106
. by -0.08377859741449356
. refusing -0.07133384048938751
. his -0.010542819276452065
. Assent -0.0006241434602998197
. to 0.0029932924080640078
. Laws 0.002839137567207217
. for -0.019388346001505852
. establishing -0.15943609178066254
. Judiciary -0.015380841679871082
. powers 0.0008433759212493896
. . 1.0

/tmp/ipython-input-558/914047137.py:3: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Token.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  print(token1.text,token2.text,token1.similarity(token2))

In [12]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [13]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid = SentimentIntensityAnalyzer()

In [15]:
sid.polarity_scores(tokens.text)

{'neg': 0.128, 'neu': 0.711, 'pos': 0.161, 'compound': 0.1779}

In [16]:
import numpy as np
import pandas as pd
df = pd.read_csv(r'/content/drive/MyDrive/Advanced AI/moviereviews.tsv', sep='\t')
df.head()

  label                                             review
0   neg  how do films like mouse hunt get into theatres...
1   neg  some talented actresses are blessed with a dem...
2   pos  this has been an extraordinary year for austra...
3   pos  according to hollywood movies made in last few...
4   neg  my first press screening of 1998 and already i...

In [17]:
df['label'].value_counts()

label
neg    1000
pos    1000
Name: count, dtype: int64

In [18]:
df.dropna(inplace=True)

In [19]:
df['label'].value_counts()

label
neg    983
pos    982
Name: count, dtype: int64

In [20]:
blanks = []
for i,lb,rv in df.itertuples():
  if type(rv) == str:
    if rv.isspace():
      blanks.append(i)
df.drop(blanks, inplace = True)
df['label'].value_counts()

label
neg    969
pos    969
Name: count, dtype: int64

In [21]:
sid.polarity_scores(df.loc[0]['review'])
df.loc[0]['label']

'neg'

In [22]:
df['scores'] = df['review'].apply(lambda review: sid.polarity_scores(review))
df.head()

,label,review,scores
0,neg,how do films like mouse hunt get into theatres...,"{'neg': 0.121, 'neu': 0.778, 'pos': 0.101, 'co..."
1,neg,some talented actresses are blessed with a dem...,"{'neg': 0.12, 'neu': 0.775, 'pos': 0.105, 'com..."
2,pos,this has been an extraordinary year for austra...,"{'neg': 0.068, 'neu': 0.781, 'pos': 0.15, 'com..."
3,pos,according to hollywood movies made in last few...,"{'neg': 0.071, 'neu': 0.782, 'pos': 0.147, 'co..."
4,neg,my first press screening of 1998 and already i...,"{'neg': 0.091, 'neu': 0.817, 'pos': 0.093, 'co..."

In [23]:
df['compound'] = df['scores'].apply(lambda score_dict: score_dict['compound'])
df.head()

,label,review,scores,compound
0,neg,how do films like mouse hunt get into theatres...,"{'neg': 0.121, 'neu': 0.778, 'pos': 0.101, 'co...",-0.9125
1,neg,some talented actresses are blessed with a dem...,"{'neg': 0.12, 'neu': 0.775, 'pos': 0.105, 'com...",-0.8618
2,pos,this has been an extraordinary year for austra...,"{'neg': 0.068, 'neu': 0.781, 'pos': 0.15, 'com...",0.9951
3,pos,according to hollywood movies made in last few...,"{'neg': 0.071, 'neu': 0.782, 'pos': 0.147, 'co...",0.9972
4,neg,my first press screening of 1998 and already i...,"{'neg': 0.091, 'neu': 0.817, 'pos': 0.093, 'co...",-0.2484

In [24]:
sid.polarity_scores(df.loc[0]['review'])
df.loc[0]['scores']

{'neg': 0.121, 'neu': 0.778, 'pos': 0.101, 'compound': -0.9125}

In [25]:
df['comp_score'] = df['compound'].apply(lambda c: 'pos' if c >=0 else 'neg')
df.head()

,label,review,scores,compound,comp_score
0,neg,how do films like mouse hunt get into theatres...,"{'neg': 0.121, 'neu': 0.778, 'pos': 0.101, 'co...",-0.9125,neg
1,neg,some talented actresses are blessed with a dem...,"{'neg': 0.12, 'neu': 0.775, 'pos': 0.105, 'com...",-0.8618,neg
2,pos,this has been an extraordinary year for austra...,"{'neg': 0.068, 'neu': 0.781, 'pos': 0.15, 'com...",0.9951,pos
3,pos,according to hollywood movies made in last few...,"{'neg': 0.071, 'neu': 0.782, 'pos': 0.147, 'co...",0.9972,pos
4,neg,my first press screening of 1998 and already i...,"{'neg': 0.091, 'neu': 0.817, 'pos': 0.093, 'co...",-0.2484,neg

In [26]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
accuracy_score(df['label'],df['comp_score'])

0.6357069143446853

In [27]:
print(confusion_matrix(df['label'],df['comp_score']))

[[427 542]
 [164 805]]

In [28]:
print(classification_report(df['label'],df['comp_score']))

              precision    recall  f1-score   support

         neg       0.72      0.44      0.55       969
         pos       0.60      0.83      0.70       969

    accuracy                           0.64      1938
   macro avg       0.66      0.64      0.62      1938
weighted avg       0.66      0.64      0.62      1938